# Gathering Data

In [1]:
from pytrends.request import TrendReq

In [2]:
pytrend = TrendReq(hl='en-US', tz=360)

In [8]:
kw_list = ["North Korea"]

In [10]:
pytrend.get_historical_interest(kw_list, 
                                 year_start=2018, month_start=1, 
                                 day_start=1, hour_start=0, 
                                 year_end=2018, month_end=2, 
                                 day_end=1, hour_end=0, 
                                 cat=0, geo='', gprop='', sleep=10)

                     North Korea  isPartial
date
2018-01-01 00:00:00           55      False
2018-01-01 01:00:00           65      False
2018-01-01 02:00:00           80      False
2018-01-01 03:00:00           77      False
2018-01-01 04:00:00           78      False
2018-01-01 05:00:00           76      False
2018-01-01 06:00:00           64      False
2018-01-01 07:00:00           55      False
2018-01-01 08:00:00           48      False
2018-01-01 09:00:00           40      False
2018-01-01 10:00:00           36      False
2018-01-01 11:00:00           34      False
2018-01-01 12:00:00           35      False
2018-01-01 13:00:00           38      False
2018-01-01 14:00:00           41      False
2018-01-01 15:00:00           43      False
2018-01-01 16:00:00           45      False
2018-01-01 17:00:00           45      False
2018-01-01 18:00:00           45      False
2018-01-01 19:00:00           43      False
2018-01-01 20:00:00           45      False
2018-01-01 21:00:00           46      False
2018-01-01 22:00:00           52      False
2018-01-01 23:00:00           62      False
2018-01-02 00:00:00           59      False
2018-01-02 01:00:00           59      False
2018-01-02 02:00:00           60      False
2018-01-02 03:00:00           61      False
2018-01-02 04:00:00           60      False
2018-01-02 05:00:00           53      False
...                          ...        ...
2018-01-30 19:00:00           17      False
2018-01-30 20:00:00           17      False
2018-01-30 21:00:00           17      False
2018-01-30 22:00:00           19      False
2018-01-30 23:00:00           22      False
2018-01-31 00:00:00           23      False
2018-01-31 01:00:00           22      False
2018-01-31 02:00:00           28      False
2018-01-31 03:00:00          100      False
2018-01-31 04:00:00           32      False
2018-01-31 05:00:00           24      False
2018-01-31 06:00:00           20      False
2018-01-31 07:00:00           14      False
2018-01-31 08:00:00           12      False
2018-01-31 09:00:00           11      False
2018-01-31 10:00:00           11      False
2018-01-31 11:00:00           12      False
2018-01-31 12:00:00           14      False
2018-01-31 13:00:00           16      False
2018-01-31 14:00:00           17      False
2018-01-31 15:00:00           17      False
2018-01-31 16:00:00           18      False
2018-01-31 17:00:00           20      False
2018-01-31 18:00:00           19      False
2018-01-31 19:00:00           19      False
2018-01-31 20:00:00           19      False
2018-01-31 21:00:00           19      False
2018-01-31 22:00:00           21      False
2018-01-31 23:00:00           24      False
2018-02-01 00:00:00           25      False

[749 rows x 2 columns]